version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"  # Mappe le port 5000 du conteneur au port 5000 de l'hôte
    volumes:
      - ./app:/app  # Monte le répertoire 'app' local dans le conteneur
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: always
